---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentic-search
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: agentic-search
    spec:
      containers:
        - name: agentic-search
          image: ghcr.io/prefeitura-rio/app-agentic-search:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: agentic-search-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: agentic-search
spec:
  selector:
    app: agentic-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
