---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eai-agent
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eai-agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: eai-agent
    spec:
      containers:
        - name: eai-agent
          image: ghcr.io/prefeitura-rio/app-agentic-search:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: eai-agent-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: eai-agent
spec:
  selector:
    app: eai-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eai-agent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eai-agent-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: eai-agent-frontend
    spec:
      containers:
        - name: eai-agent-frontend
          image: ghcr.io/prefeitura-rio/app-agentic-search-frontend:latest
          ports:
            - containerPort: 80
          # Adicione recursos para garantir que o pod tenha CPU e memória suficientes
          # Isso pode ajudar a evitar lentidão devido a restrições de recursos
          resources:
            requests:
              cpu: "200m"  # Solicita 0.2 de um core de CPU
              memory: "256Mi" # Solicita 256 Megabytes de memória
            limits:
              cpu: "500m"  # Limita a 0.5 de um core de CPU (permite bursts)
              memory: "512Mi" # Limita a 512 Megabytes de memória
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: eai-agent-frontend
spec:
  selector:
    app: eai-agent-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
