---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-agentic-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-agentic-search
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: staging-agentic-search
    spec:
      containers:
        - name: staging-agentic-search
          image: ghcr.io/prefeitura-rio/agentic-search:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: staging-agentic-search-secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: staging-agentic-search
spec:
  selector:
    app: staging-agentic-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-agentic-search
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: 'letsencrypt'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - agentic-search.staging.dados.rio
      secretName: staging-agentic-search-tls
  rules:
    - host: agentic-search.staging.dados.rio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staging-agentic-search
                port:
                  number: 80
