TOOL_CALLING = """
You are an evaluation assistant evaluating questions and tool calls to
determine whether the tool called would answer the question. The tool
calls have been generated by a separate agent, and chosen from the list of
tools provided below. It is your job to decide whether that agent chose
the right tool to call.

    [BEGIN DATA]
    ************
    [Question]: {question}
    ************
    [Tool Called]: {tool_call}
    [END DATA]

LABEL:
"incorrect" means that the chosen tool would not answer the question,
the tool includes information that is not presented in the question,
or that the tool signature includes parameter values that don't match
the formats specified in the tool signatures below.

"correct" means the correct tool call was chosen, the correct parameters
were extracted from the question, the tool call generated is runnable and correct,
and that no outside information not present in the question was used
in the generated question.

    [Tool Definitions]: {tool_definitions}

OUTPUT FORMAT

```
{
    'label':str
}
```
"""

SEARCH_QUERY_EFFECTIVENESS_LLM_JUDGE_PROMPT = """
In this task, you will be presented with an original 'user_query' and a 'search_tool_query' that an agent generated based on the user's query to use with a search tool. Your objective is to evaluate if the 'search_tool_query' is an effective and accurate representation of the user's core search intent, suitable for yielding relevant results from a search tool. An effective search query is concise, captures the essential keywords or concepts, and omits conversational or irrelevant parts of the user's query.

The 'label' field in your JSON output should be a single word: either "effective" or "innefective."
- "effective" indicates that the 'search_tool_query' is a good, concise representation of the user's search intent and is likely to yield relevant search results.
- "innefective" indicates that the 'search_tool_query' is poorly formulated, misses key aspects, is too broad, too narrow, or misinterprets the intent, making it unlikely to yield good search results.

Consider these examples:
Good Simplification:
- user_query: "aqui em casa está um inferno porque alguém estacionou na porta da minha garagem, a prefeitura tem que dar um jeito nisso"
- search_tool_query: "estacionamento irregular"
(This is good because it extracts the core searchable problem.)

Bad Simplification:
- user_query: "meu filho fez 5 anos e eu quero matricular ele na creche, o que eu faço?"
- search_tool_query: "creche 5 anos"
(This is bad because "5 anos" might be too specific or misinterpreted by a search tool looking for age ranges or program names. A better search might be "matrícula creche infantil" or "vaga creche pública [cidade]" if context allows.)
Correct Simplification for the bad example:
- user_query: "meu filho fez 5 anos e eu quero matricular ele na creche, o que eu faço?"
- search_tool_query: "creche infantil" (or similar, like "matrícula creche pública")

After analyzing, you must write a detailed explanation. Your 'explanation' should:
1. Briefly state the core search intent you derived from the 'user_query'.
2. Analyze how well the 'search_tool_query' captures this intent.
3. Point out if essential information was kept, if irrelevant information was correctly discarded, and if the 'search_tool_query' is specific enough without being overly narrow or broad.
4. If 'innefective', explain why it's problematic (e.g., what's missing, what's wrong, why it might lead to poor results) and you may suggest a better search query.

[BEGIN DATA]
User Query: {user_query}
Search Tool Query: {search_tool_query}
[END DATA]
Please analyze the data carefully and provide your explanation and label in the specified JSON format.

explanation: Identify the user's core search intent. Evaluate if the search_tool_query effectively captures this intent for a search tool, noting strengths or weaknesses.
label: "effective" or "innefective"

OUTPUT FORMAT

```
{
    'label':str
}
```
"""