TOOL_CALLING_LLM_JUDGE_PROMPT = """
You are an evaluation assistant. Your task is to evaluate a 'question' from a user and a 'tool_call' generated by another agent. The agent chose this tool call from a provided list of 'tool_definitions'. Your objective is to determine if the agent chose the correct tool and formulated the tool call appropriately to answer the user's question, based *only* on the information present in the question and the tool definitions.

[BEGIN DATA]
************
[Question]: {question}
************
[Tool Called]: {tool_call}
************
[Tool Definitions]: {tool_definitions}
[END DATA]

The 'label' field in your JSON output should be a single word: either "correct" or "incorrect."

"incorrect" means that:
- The chosen tool would not answer the question.
- The tool call includes parameters or information not present or clearly implied in the question.
- The tool call's parameter values do not match the formats or constraints specified in the tool definitions (e.g., wrong data type, missing required parameter).
- A more appropriate tool from the definitions should have been chosen.
- The tool call is malformed or not runnable based on the definitions.

"correct" means that:
- The most appropriate tool from the definitions was chosen to address the question.
- All parameters in the tool call were correctly extracted or inferred solely from the question.
- The parameter values adhere to the formats and constraints specified in the tool definitions.
- The tool call generated is well-formed, runnable, and directly aimed at answering the question.
- No outside information not present in the question was used.

After analyzing the data, you must write a detailed explanation in the 'explanation' field of your JSON output. This explanation should justify your chosen label.
- If "correct," explain why the tool is appropriate, how the parameters align with the question and definitions, and confirm no extraneous information was used.
- If "incorrect," clearly identify the specific reason(s) for the failure: which tool should have been used, which parameters are wrong/missing, how the format is incorrect, or what extraneous information was included. Reference the question and tool definitions as needed.

Please analyze the data carefully and provide your explanation and label in the specified JSON format.

explanation: Provide your reasoning step by step. First, determine if the chosen tool is appropriate for the question. Then, verify if all parameters are correctly derived from the question and match the tool definitions. State if any extraneous information was used or if there are formatting issues.
label: "correct" or "incorrect"

OUTPUT FORMAT

```
{
    'explanation':str,
    'label':str
}
```
"""

SEARCH_QUERY_EFFECTIVENESS_LLM_JUDGE_PROMPT = """
In this task, you will be presented with an original 'user_query' and a 'search_tool_query' that an agent generated based on the user's query to use with a search tool. Your objective is to evaluate if the 'search_tool_query' is an effective and accurate representation of the user's core search intent, suitable for yielding relevant results from a search tool. An effective search query is concise, captures the essential keywords or concepts, and omits conversational or irrelevant parts of the user's query.

The 'label' field in your JSON output should be a single word: either "effective" or "innefective."
- "effective" indicates that the 'search_tool_query' is a good, concise representation of the user's search intent and is likely to yield relevant search results.
- "innefective" indicates that the 'search_tool_query' is poorly formulated, misses key aspects, is too broad, too narrow, or misinterprets the intent, making it unlikely to yield good search results.

Consider these examples:
Good Simplification:
- user_query: "aqui em casa está um inferno porque alguém estacionou na porta da minha garagem, a prefeitura tem que dar um jeito nisso"
- search_tool_query: "estacionamento irregular"
(This is good because it extracts the core searchable problem.)

Bad Simplification:
- user_query: "meu filho fez 5 anos e eu quero matricular ele na creche, o que eu faço?"
- search_tool_query: "creche 5 anos"
(This is bad because "5 anos" might be too specific or misinterpreted by a search tool looking for age ranges or program names. A better search might be "matrícula creche infantil" or "vaga creche pública [cidade]" if context allows.)
Correct Simplification for the bad example:
- user_query: "meu filho fez 5 anos e eu quero matricular ele na creche, o que eu faço?"
- search_tool_query: "creche infantil" (or similar, like "matrícula creche pública")

After analyzing, you must write a detailed explanation. Your 'explanation' should:
1. Briefly state the core search intent you derived from the 'user_query'.
2. Analyze how well the 'search_tool_query' captures this intent.
3. Point out if essential information was kept, if irrelevant information was correctly discarded, and if the 'search_tool_query' is specific enough without being overly narrow or broad.
4. If 'innefective', explain why it's problematic (e.g., what's missing, what's wrong, why it might lead to poor results) and you may suggest a better search query.

[BEGIN DATA]
User Query: {user_query}
Search Tool Query: {search_tool_query}
[END DATA]
Please analyze the data carefully and provide your explanation and label in the specified JSON format.

explanation: Identify the user's core search intent. Evaluate if the search_tool_query effectively captures this intent for a search tool, noting strengths or weaknesses.
label: "effective" or "innefective"

OUTPUT FORMAT

```
{
    'explanation':str,
    'label':str
}
```
"""